In [3]:
# Ejercicio 2
# Dado un array 0,15,25,30,100, convertir a grados F usando la formula F = C * (9/5) + 32. Realizar la operacion en una sola línea de código (vectorización)
import numpy as np

grados_c = np.array([0, 15, 25, 30, 100])
fahrenheit = grados_c * (9/5) + 32
print("Temperatura en C°: ", grados_c)
print("Temperatura en F°: ", fahrenheit)

Temperatura en C°:  [  0  15  25  30 100]
Temperatura en F°:  [ 32.  59.  77.  86. 212.]


# Ejercicio 3: Indexación y Slicing

Crea una matriz 3x3 con números del 1 al 9. A partir de ella, extrae:

a) El número en la segunda fila, tercera columna (el 6).

b) La segunda fila completa.

c) La tercera columna completa.

In [5]:
matriz = np.arange(1, 10).reshape(3, 3)
print("Matriz:\n", matriz)

# a) Número en la segunda fila, tercera columna
num_a = matriz[1, 2]
print("Número en la segunda fila, tercera columna:", num_a)

# b) Segunda fila completa
fila_b = matriz[1, :]
print("Segunda fila completa:", fila_b)

# c) Tercera columna completa
columna_c = matriz[:, 2]
print("Tercera columna completa:", columna_c)


Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Número en la segunda fila, tercera columna: 6
Segunda fila completa: [4 5 6]
Tercera columna completa: [3 6 9]
